import os
import argparse
import pandas as pd
import json
import time
import glob
import hashlib
import chromadb
import fitz  # PyMuPDF for PDF text extraction
import base64
import re
from pathlib import Path

# Vertex AI
from google import genai
from google.genai import types
from google.genai.types import Content, Part, GenerationConfig, ToolConfig
from google.genai import errors
from vertexai.vision_models import MultiModalEmbeddingModel

# Langchain
from langchain_text_splitters import CharacterTextSplitter, RecursiveCharacterTextSplitter
from semantic_splitter import SemanticChunker
import agent_tools

# Setup
GCP_PROJECT = os.environ["GCP_PROJECT"]
GCP_LOCATION = "us-central1"
EMBEDDING_MODEL = "text-embedding-004"
EMBEDDING_DIMENSION = 256
GENERATIVE_MODEL = "gemini-2.0-flash-001"
INPUT_FOLDER = "input-datasets"
OUTPUT_FOLDER = "outputs"
CHROMADB_HOST = "llm-rag-chromadb"
CHROMADB_PORT = 8000

#############################################################################
#                       Initialize the LLM Client                           #
llm_client = genai.Client(
    vertexai=True, project=GCP_PROJECT, location=GCP_LOCATION)
#############################################################################

# Initialize the GenerativeModel with specific system instructions
SYSTEM_INSTRUCTION = """
You are an AI assistant specialized in Gianfranco Ferré and fashion archive research. Your responses are based solely on the information provided in the text chunks given to you. Do not use any external knowledge or make assumptions beyond what is explicitly stated in these chunks.

When answering a query:
1. Carefully read all the text chunks provided.
2. Identify the most relevant information from these chunks to address the user's question.
3. Formulate your response using only the information found in the given chunks.
4. If the provided chunks do not contain sufficient information to answer the query, state that you don't have enough information to provide a complete answer.
5. Always maintain a professional and knowledgeable tone, befitting a Ferré archive expert.
6. If there are contradictions in the provided chunks, mention this in your response and explain the different viewpoints presented.

Remember:
- You are an expert in Ferré and fashion, but your knowledge is limited to the information in the provided chunks.
- Do not invent information or draw from knowledge outside of the given text chunks.
- If asked about topics unrelated to Ferré or fashion, politely redirect the conversation back to archive-related subjects.
- Be concise in your responses while ensuring you cover all relevant information from the chunks.

Your goal is to provide accurate, helpful information about Ferré and fashion based solely on the content of the text chunks you receive with each query.
"""

# Load Ferre mappings if available (generated by temp_llm_metadata.py or manually)
ferre_mappings = {}
for candidate in ("ferre_mappings.json", "ferre_mappings_llm.json"):
    if os.path.exists(candidate):
        try:
            with open(candidate, "r") as f:
                ferre_mappings = json.load(f)
            print(f"Loaded metadata mapping from {candidate}")
            break
        except Exception as e:
            print(f"Failed to load {candidate}: {e}")
            ferre_mappings = {}

def generate_query_embedding(query):
    kwargs = {
        "output_dimensionality": EMBEDDING_DIMENSION
    }
    response = llm_client.models.embed_content(
        model=EMBEDDING_MODEL,
        contents=query,
        config=types.EmbedContentConfig(**kwargs)
    )
    return response.embeddings[0].values


def generate_text_embeddings(chunks, dimensionality: int = 256, batch_size=250, max_retries=5, retry_delay=5):
    # Max batch size is 250 for Vertex AI
    all_embeddings = []

    for i in range(0, len(chunks), batch_size):
        batch = chunks[i:i+batch_size]

        # Retry logic with exponential backoff        pip list | grep langchain
        retry_count = 0
        while retry_count <= max_retries:
            try:
                response = llm_client.models.embed_content(
                    model=EMBEDDING_MODEL,
                    contents=batch,
                    config=types.EmbedContentConfig(
                        output_dimensionality=dimensionality),
                )
                all_embeddings.extend(
                    [embedding.values for embedding in response.embeddings])
                break

            except errors.APIError as e:
                retry_count += 1
                if retry_count > max_retries:
                    print(
                        f"Failed to generate embeddings after {max_retries} attempts. Last error: {str(e)}")
                    raise

                # Calculate delay with exponential backoff
                wait_time = retry_delay * (2 ** (retry_count - 1))
                print(
                    f"API error (code: {e.code}): {e.message}. Retrying in {wait_time} seconds (attempt {retry_count}/{max_retries})...")
                time.sleep(wait_time)

    return all_embeddings


def load_text_embeddings(df, collection, batch_size=500):

    # Generate ids
    df["id"] = df.index.astype(str)

    # Determine key column: prefer 'doc' (PDF-derived), else 'book'
    key_col = "doc" if "doc" in df.columns else "book" if "book" in df.columns else None
    if key_col is None:
        raise ValueError("Dataframe must contain either 'doc' or 'book' column for metadata mapping")

    # Create hashed prefix from doc/book name
    hashed_keys = df[key_col].astype(str).apply(lambda x: hashlib.sha256(x.encode()).hexdigest()[:16])
    df["id"] = hashed_keys + "-" + df["id"]

    # Process data in batches
    total_inserted = 0
    for i in range(0, df.shape[0], batch_size):
        # Create a copy of the batch and reset the index
        batch = df.iloc[i:i+batch_size].copy().reset_index(drop=True)

        ids = batch["id"].tolist()
        documents = batch["chunk"].tolist()
        embeddings = batch["embedding"].tolist()

        # Build per-item metadata using ferre_mappings if available
        metadatas = []
        for key in batch[key_col].tolist():
            item_meta = {key_col: key}
            mapping_key = key
            if mapping_key in ferre_mappings:
                try:
                    # Merge mapping fields into item_meta
                    item_meta.update(ferre_mappings[mapping_key])
                except Exception:
                    pass
            metadatas.append(item_meta)

        collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas,
            embeddings=embeddings
        )
        total_inserted += len(batch)
        print(f"Inserted {total_inserted} items...")

    print(
        f"Finished inserting {total_inserted} items into collection '{collection.name}'")


def load_image_embeddings(df, collection, batch_size=500):
    """Load image embeddings into ChromaDB collection."""

    # Use the 'id' column directly if it exists, otherwise generate from filename
    if "id" not in df.columns:
        df["id"] = df["filename"].astype(str)

    # Process data in batches
    total_inserted = 0
    for i in range(0, df.shape[0], batch_size):
        # Create a copy of the batch and reset the index
        batch = df.iloc[i:i+batch_size].copy().reset_index(drop=True)

        ids = batch["id"].tolist()
        embeddings = batch["embedding"].tolist()

        # Build metadata from available columns
        metadatas = []
        for idx, row in batch.iterrows():
            item_meta = {}
            if "filename" in row:
                item_meta["filename"] = str(row["filename"])
            if "path" in row:
                item_meta["path"] = str(row["path"])
            if "season" in row:
                item_meta["season"] = str(row["season"])
            metadatas.append(item_meta)

        # Use filename as document text (for reference/search)
        documents = batch["filename"].astype(str).tolist() if "filename" in batch.columns else ids

        collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas,
            embeddings=embeddings
        )
        total_inserted += len(batch)
        print(f"  Inserted {total_inserted} items...")

    print(
        f"  Finished inserting {total_inserted} items into collection '{collection.name}'")


def chunk(method="char-split", source="pdf"):
    print("chunk()")

    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    if source == "pdf":
        pdf_dir = os.path.join(INPUT_FOLDER, "ferre-notes-lessons")
        pdf_files = glob.glob(os.path.join(pdf_dir, "*.pdf"))
        print("Number of PDFs to process:", len(pdf_files))

        for pdf_file in pdf_files:
            print("Processing PDF:", pdf_file)
            filename = os.path.basename(pdf_file)
            doc_name = os.path.splitext(filename)[0]

            try:
                doc = fitz.open(pdf_file)
            except Exception as e:
                print(f"Failed to open {pdf_file}: {e}")
                continue

            # Extract full text (or consider first N pages for metadata)
            input_text = "\n".join([p.get_text() for p in doc])

            text_chunks = None
            if method == "char-split":
                chunk_size = 350
                chunk_overlap = 20
                text_splitter = CharacterTextSplitter(
                    chunk_size=chunk_size, chunk_overlap=chunk_overlap, separator='', strip_whitespace=False)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "recursive-split":
                chunk_size = 350
                text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "semantic-split":
                text_splitter = SemanticChunker(embedding_function=generate_text_embeddings)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]

            if text_chunks is not None:
                data_df = pd.DataFrame(text_chunks, columns=["chunk"])
                data_df["doc"] = doc_name
                print("Shape:", data_df.shape)
                print(data_df.head())
                jsonl_filename = os.path.join(OUTPUT_FOLDER, f"chunks-{method}-{doc_name}.jsonl")
                with open(jsonl_filename, "w") as json_file:
                    json_file.write(data_df.to_json(orient='records', lines=True))
    else:
        # Fallback to original text-based chunking
        text_files = glob.glob(os.path.join(INPUT_FOLDER, "books", "*.txt"))
        print("Number of text files to process:", len(text_files))
        for text_file in text_files:
            print("Processing file:", text_file)
            filename = os.path.basename(text_file)
            book_name = filename.split(".")[0]
            with open(text_file) as f:
                input_text = f.read()

            text_chunks = None
            if method == "char-split":
                chunk_size = 350
                chunk_overlap = 20
                text_splitter = CharacterTextSplitter(
                    chunk_size=chunk_size, chunk_overlap=chunk_overlap, separator='', strip_whitespace=False)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "recursive-split":
                chunk_size = 350
                text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "semantic-split":
                text_splitter = SemanticChunker(embedding_function=generate_text_embeddings)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]

            if text_chunks is not None:
                data_df = pd.DataFrame(text_chunks, columns=["chunk"])
                data_df["book"] = book_name
                print("Shape:", data_df.shape)
                print(data_df.head())
                jsonl_filename = os.path.join(OUTPUT_FOLDER, f"chunks-{method}-{book_name}.jsonl")
                with open(jsonl_filename, "w") as json_file:
                    json_file.write(data_df.to_json(orient='records', lines=True))


def embed(method="char-split"):
    print("embed()")

    # Get the list of chunk files
    jsonl_files = glob.glob(os.path.join(
        OUTPUT_FOLDER, f"chunks-{method}-*.jsonl"))
    print("Number of files to process:", len(jsonl_files))

    # Process
    for jsonl_file in jsonl_files:
        print("Processing file:", jsonl_file)

        data_df = pd.read_json(jsonl_file, lines=True)
        print("Shape:", data_df.shape)
        print(data_df.head())

        chunks = data_df["chunk"].values
        chunks = chunks.tolist()
        if method == "semantic-split":
            embeddings = generate_text_embeddings(
                chunks, EMBEDDING_DIMENSION, batch_size=15)
        else:
            embeddings = generate_text_embeddings(
                chunks, EMBEDDING_DIMENSION, batch_size=100)
        data_df["embedding"] = embeddings

        time.sleep(5)

        # Save
        print("Shape:", data_df.shape)
        print(data_df.head())

        jsonl_filename = jsonl_file.replace("chunks-", "embeddings-")
        with open(jsonl_filename, "w") as json_file:
            json_file.write(data_df.to_json(orient='records', lines=True))


def generate_image_embeddings(image_paths, dimensionality: int = 256, batch_size=1, max_retries=1, retry_delay=5):
    """Generate embeddings for images using Vertex AI's MultiModalEmbeddingModel."""
    import vertexai

    # Initialize Vertex AI
    vertexai.init(project=GCP_PROJECT, location=GCP_LOCATION)
    model = MultiModalEmbeddingModel.from_pretrained("multimodalembedding@001")

    all_embeddings = []
    failed_count = 0

    for idx, img_path in enumerate(image_paths, 1):
        try:
            filename = Path(img_path).name

            # Retry logic with exponential backoff
            retry_count = 0
            success = False
            while retry_count <= max_retries:
                try:
                    from vertexai.vision_models import Image

                    # Load image using Vertex AI Image class
                    image = Image.load_from_file(img_path)

                    # Use the multimodal embedding model to get embeddings
                    response = model.get_embeddings(
                        image=image,
                        dimension=1408
                    )

                    if response and response.image_embedding:
                        all_embeddings.append(response.image_embedding)
                        print(f"  [{idx}/{len(image_paths)}] ✓ {filename}")
                        success = True
                        break
                    else:
                        raise ValueError(f"No embeddings returned for {filename}")

                except Exception as e:
                    retry_count += 1
                    if retry_count > max_retries:
                        print(f"  [{idx}/{len(image_paths)}] ✗ {filename} - Failed after {max_retries} retries: {str(e)}")
                        failed_count += 1
                        break

                    # Calculate delay with exponential backoff
                    wait_time = retry_delay * (2 ** (retry_count - 1))
                    print(f"  [{idx}/{len(image_paths)}] Retrying {filename} in {wait_time}s... (attempt {retry_count}/{max_retries})")
                    time.sleep(wait_time)

        except Exception as e:
            print(f"  [{idx}/{len(image_paths)}] ✗ Error processing {Path(img_path).name}: {e}")
            failed_count += 1

    print(f"\n✓ Generated {len(all_embeddings)} embeddings ({failed_count} failed)")
    return all_embeddings


def embed_images(images_folder="input-datasets/ferre-designs"):
    """Generate embeddings for all images organized by season folders."""
    print(f"embed_images() - Processing images from {images_folder}")
    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    # Find all image files and group by season folder
    image_extensions = ('*.jpg', '*.jpeg', '*.png', '*.gif', '*.webp')
    seasons_data = {}  # {season_key: [image_paths]}

    for root, dirs, files in os.walk(images_folder):
        for file in files:
            if any(file.lower().endswith(ext.replace('*', '')) for ext in image_extensions):
                img_path = os.path.join(root, file)

                # Extract season from folder path
                # e.g., "input-datasets/ferre-designs/ALTA-MODA/FW1986-87" -> "FW1986-87"
                rel_path = os.path.relpath(img_path, images_folder)
                path_parts = rel_path.split(os.sep)

                # Use the second-to-last folder as season (e.g., "ALTA-MODA" or folder structure)
                if len(path_parts) >= 2:
                    season_folder = path_parts[-2]  # Parent folder
                else:
                    season_folder = "unknown"

                if season_folder not in seasons_data:
                    seasons_data[season_folder] = []
                seasons_data[season_folder].append(img_path)

    if not seasons_data:
        print(f"⚠ No image files found in {images_folder}")
        return

    print(f"Found {sum(len(v) for v in seasons_data.values())} image files across {len(seasons_data)} seasons")
    print(f"Seasons: {', '.join(sorted(seasons_data.keys()))}")

    # Process each season
    for season_folder, image_files in sorted(seasons_data.items()):
        print(f"\n→ Processing season: {season_folder} ({len(image_files)} images)")

        image_files = sorted(image_files)

        # Generate embeddings for this season
        embeddings = generate_image_embeddings(image_files, EMBEDDING_DIMENSION)

        # Create dataframe with image metadata
        data = []
        for img_path, embedding in zip(image_files, embeddings):
            filename = os.path.basename(img_path)

            data.append({
                "id": hashlib.md5(img_path.encode()).hexdigest(),
                "filename": filename,
                "path": img_path,
                "season": season_folder,
                "embedding": embedding,
                "text": f"{season_folder} - {filename}"  # For text-based querying
            })

        # Save embeddings for this season
        output_file = os.path.join(OUTPUT_FOLDER, f"embeddings-images-{season_folder}.jsonl")
        df = pd.DataFrame(data)

        with open(output_file, "w") as f:
            f.write(df.to_json(orient='records', lines=True))

        print(f"  ✓ Saved {len(df)} embeddings to {output_file}")

    print(f"\n✓ Image embeddings complete for all {len(seasons_data)} seasons")


def load(method="char-split"):
    print("load()")

    # Clear Cache
    chromadb.api.client.SharedSystemClient.clear_system_cache()

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)

    # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
    collection_name = f"{method}-collection"
    print("Creating collection:", collection_name)

    try:
        # Clear out any existing items in the collection
        client.delete_collection(name=collection_name)
        print(f"Deleted existing collection '{collection_name}'")
    except Exception:
        print(f"Collection '{collection_name}' did not exist. Creating new.")

    collection = client.create_collection(
        name=collection_name, metadata={"hnsw:space": "cosine"})
    print(f"Created new empty collection '{collection_name}'")
    print("Collection:", collection)

    # Get the list of embedding files
    jsonl_files = glob.glob(os.path.join(
        OUTPUT_FOLDER, f"embeddings-{method}-*.jsonl"))
    print("Number of files to process:", len(jsonl_files))

    # Process
    for jsonl_file in jsonl_files:
        print("Processing file:", jsonl_file)

        data_df = pd.read_json(jsonl_file, lines=True)
        print("Shape:", data_df.shape)
        print(data_df.head())

        # Load data
        load_text_embeddings(data_df, collection)


def load_images():
    """Load image embeddings into ChromaDB, creating separate collections per season."""
    print("load_images()")

    # Clear Cache
    chromadb.api.client.SharedSystemClient.clear_system_cache()

    # Connect to chroma DB with retry logic
    max_retries = 10
    retry_delay = 1
    client = None
    for attempt in range(max_retries):
        try:
            client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)
            print(f"✓ Connected to ChromaDB on attempt {attempt + 1}")
            break
        except (ValueError, ConnectionError) as e:
            if attempt < max_retries - 1:
                print(f"⚠ ChromaDB not ready (attempt {attempt + 1}/{max_retries}), retrying in {retry_delay}s...")
                time.sleep(retry_delay)
                retry_delay = min(retry_delay * 1.5, 5)
            else:
                print(f"✗ Failed to connect to ChromaDB after {max_retries} attempts")
                raise

    if client is None:
        raise RuntimeError("Failed to connect to ChromaDB")

    # Find all season embedding files
    embedding_files = glob.glob(os.path.join(OUTPUT_FOLDER, "embeddings-images-*.jsonl"))

    if not embedding_files:
        print(f"⚠ No image embeddings found in {OUTPUT_FOLDER}. Run --embed-images first.")
        return

    print(f"Found {len(embedding_files)} season(s) to load")

    # Load each season's embeddings into its own collection
    total_loaded = 0
    for jsonl_file in sorted(embedding_files):
        # Extract season name from filename
        # e.g., "embeddings-images-FW1986-87.jsonl" -> "FW1986-87"
        season = os.path.basename(jsonl_file).replace("embeddings-images-", "").replace(".jsonl", "")
        collection_name = f"images-{season}"

        print(f"\n→ Loading season: {season}")
        print(f"  Collection: {collection_name}")

        # Delete existing collection if it exists
        try:
            client.delete_collection(name=collection_name)
            print(f"  Deleted existing collection")
        except Exception:
            pass

        # Create new collection
        collection = client.create_collection(
            name=collection_name, metadata={"hnsw:space": "cosine"})
        print(f"  Created collection")

        # Load embeddings
        print(f"  Loading from {jsonl_file}")
        data_df = pd.read_json(jsonl_file, lines=True)
        print(f"  Shape: {data_df.shape}")

        # Load data using image-specific loader
        load_image_embeddings(data_df, collection)
        total_loaded += len(data_df)
        print(f"  ✓ Loaded {len(data_df)} images")

    print(f"\n✓ Image loading complete. Total: {total_loaded} images across {len(embedding_files)} seasons")

def query(method="char-split"):
    print("load()")

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)

    # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
    collection_name = f"{method}-collection"

    query = "How is tolminc cheese made?"
    query_embedding = generate_query_embedding(query)
    print("Embedding values:", query_embedding)

    # Get the collection
    collection = client.get_collection(name=collection_name)

    # # 1: Query based on embedding value
    # results = collection.query(
    # 	query_embeddings=[query_embedding],
    # 	n_results=10
    # )
    # print("Query:", query)
    # print("\n\nResults:", results)

    # # 2: Query based on embedding value + metadata filter
    # results = collection.query(
    # 	query_embeddings=[query_embedding],
    # 	n_results=10,
    # 	where={"book":"The Complete Book of Cheese"}
    # )
    # print("Query:", query)
    # print("\n\nResults:", results)

    # # 3: Query based on embedding value + lexical search filter
    # search_string = "Italian"
    # results = collection.query(
    # 	query_embeddings=[query_embedding],
    # 	n_results=10,
    # 	where_document={"$contains": search_string}
    # )
    # print("Query:", query)
    # print("\n\nResults:", results)

    # 4: Query based on embedding value + lexical search filter
    search_string = "Italian"
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=10,
        where={"book": "The Complete Book of Cheese"},
        where_document={"$contains": search_string}
    )
    print("Query:", query)
    print("\n\nResults:", results)


def chat(method="char-split"):
    print("chat()")

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)
    # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
    collection_name = f"{method}-collection"

    query = "How is cheese made?"
    query_embedding = generate_query_embedding(query)
    print("Query:", query)
    print("Embedding values:", query_embedding)
    # Get the collection
    collection = client.get_collection(name=collection_name)

    # Query based on embedding value
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=10
    )
    print("\n\nResults:", results)

    print(len(results["documents"][0]))

    INPUT_PROMPT = f"""
	{query}
	{"\n".join(results["documents"][0])}
	"""

    print("INPUT_PROMPT: ", INPUT_PROMPT)
    response = llm_client.models.generate_content(
        model=GENERATIVE_MODEL, contents=INPUT_PROMPT
    )
    generated_text = response.text

    print("LLM Response:", generated_text)


def get(method="char-split"):
    print("get()")

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)
    # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
    collection_name = f"{method}-collection"

    # Get the collection
    collection = client.get_collection(name=collection_name)

    # Get documents with filters
    results = collection.get(
        where={"book": "The Complete Book of Cheese"},
        limit=10
    )
    print("\n\nResults:", results)

# TODO: Adapt this function for the Ferre Archive Project. 
# Implement agent function that uses LLM to determine which tools to call, executes them, and feeds results back to LLM for final response

# def agent(method="char-split"):
#     print("agent()")

#     # Connect to chroma DB
#     client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)
#     # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
#     collection_name = f"{method}-collection"
#     # Get the collection
#     collection = client.get_collection(name=collection_name)

#     # User prompt
#     user_prompt_content = Content(
#         role="user",
#         parts=[
#             Part(text="Describe where cheese making is important in Pavlos's book?"),
#         ],
#     )

#     # Step 1: Prompt LLM to find the tool(s) to execute to find the relevant chunks in vector db
#     print("user_prompt_content: ", user_prompt_content)
#     response = llm_client.models.generate_content(
#         model=GENERATIVE_MODEL,
#         contents=user_prompt_content,
#         config=types.GenerateContentConfig(
#             temperature=0,
#             tools=[agent_tools.cheese_expert_tool],
#             tool_config=types.ToolConfig(
#                 function_calling_config=types.FunctionCallingConfig(
#                     mode="any"
#                 )
#             )
#         )
#     )
#     print("LLM Response:", response)

#     # Step 2: Execute the function and send chunks back to LLM to answer get the final response
#     function_calls = [part.function_call for part in response.candidates[0].content.parts if part.function_call]
#     print("Function calls:", function_calls)
#     function_responses = agent_tools.execute_function_calls(
#         function_calls, collection, embed_func=generate_query_embedding)
#     if len(function_responses) == 0:
#         print("Function calls did not result in any responses...")
#     else:
#         # Call LLM with retrieved responses
#         response = llm_client.models.generate_content(
#             model=GENERATIVE_MODEL,
#             contents=[
#                 user_prompt_content,  # User prompt
#                 response.candidates[0].content,  # Function call response
#                 Content(
#                     parts=function_responses
#                 ),
#             ],
#             config=types.GenerateContentConfig(
#                 tools=[agent_tools.cheese_expert_tool]
#             )
#         )
#         print("LLM Response:", response)


def main(args=None):
    print("CLI Arguments:", args)

    if args.chunk:
        chunk(method=args.chunk_type)

    if args.embed:
        embed(method=args.chunk_type)

    if args.embed_images:
        embed_images()

    if args.load:
        load(method=args.chunk_type)

    if args.load_images:
        load_images()

    if args.query:
        query(method=args.chunk_type)

    if args.chat:
        chat(method=args.chunk_type)

    if args.get:
        get(method=args.chunk_type)

    # TODO - Adapt this function for the Ferre Archive Project.
    # if args.agent:
    #     agent(method=args.chunk_type)


if __name__ == "__main__":
    # Generate the inputs arguments parser
    # if you type into the terminal '--help', it will provide the description
    parser = argparse.ArgumentParser(description="CLI")

    parser.add_argument(
        "--chunk",
        action="store_true",
        help="Chunk text",
    )
    parser.add_argument(
        "--embed",
        action="store_true",
        help="Generate embeddings",
    )
    parser.add_argument(
        "--load",
        action="store_true",
        help="Load embeddings to vector db",
    )
    parser.add_argument(
        "--query",
        action="store_true",
        help="Query vector db",
    )
    parser.add_argument(
        "--chat",
        action="store_true",
        help="Chat with LLM",
    )
    parser.add_argument(
        "--get",
        action="store_true",
        help="Get documents from vector db",
    )
    parser.add_argument(
        "--agent",
        action="store_true",
        help="Chat with LLM Agent",
    )
    parser.add_argument(
        "--embed-images",
        action="store_true",
        help="Generate embeddings for images",
    )
    parser.add_argument(
        "--load-images",
        action="store_true",
        help="Load image embeddings to vector db",
    )
    parser.add_argument("--chunk_type", default="char-split",
                        help="char-split | recursive-split | semantic-split")

    args = parser.parse_args()

    main(args)
