import os
import argparse
import pandas as pd
import json
import time
import glob
import hashlib
import chromadb
import fitz  # PyMuPDF for PDF text extraction

# Vertex AI
from google import genai
from google.genai import types
from google.genai.types import Content, Part, GenerationConfig, ToolConfig
from google.genai import errors

# Langchain
from langchain_text_splitters import CharacterTextSplitter, RecursiveCharacterTextSplitter
from semantic_splitter import SemanticChunker
import agent_tools

# Setup
GCP_PROJECT = os.environ["GCP_PROJECT"]
GCP_LOCATION = "us-central1"
EMBEDDING_MODEL = "text-embedding-004"
EMBEDDING_DIMENSION = 256
GENERATIVE_MODEL = "gemini-2.0-flash-001"
INPUT_FOLDER = "input-datasets"
OUTPUT_FOLDER = "outputs"
CHROMADB_HOST = "llm-rag-chromadb"
CHROMADB_PORT = 8000

#############################################################################
#                       Initialize the LLM Client                           #
llm_client = genai.Client(
    vertexai=True, project=GCP_PROJECT, location=GCP_LOCATION)
#############################################################################

# Initialize the GenerativeModel with specific system instructions
SYSTEM_INSTRUCTION = """
You are an AI assistant specialized in Gianfranco Ferré and fashion archive research. Your responses are based solely on the information provided in the text chunks given to you. Do not use any external knowledge or make assumptions beyond what is explicitly stated in these chunks.

When answering a query:
1. Carefully read all the text chunks provided.
2. Identify the most relevant information from these chunks to address the user's question.
3. Formulate your response using only the information found in the given chunks.
4. If the provided chunks do not contain sufficient information to answer the query, state that you don't have enough information to provide a complete answer.
5. Always maintain a professional and knowledgeable tone, befitting a Ferré archive expert.
6. If there are contradictions in the provided chunks, mention this in your response and explain the different viewpoints presented.

Remember:
- You are an expert in Ferré and fashion, but your knowledge is limited to the information in the provided chunks.
- Do not invent information or draw from knowledge outside of the given text chunks.
- If asked about topics unrelated to Ferré or fashion, politely redirect the conversation back to archive-related subjects.
- Be concise in your responses while ensuring you cover all relevant information from the chunks.

Your goal is to provide accurate, helpful information about Ferré and fashion based solely on the content of the text chunks you receive with each query.
"""

# Load Ferre mappings if available (generated by temp_llm_metadata.py or manually)
ferre_mappings = {}
for candidate in ("ferre_mappings.json", "ferre_mappings_llm.json",  
                 os.path.join("metadata", "ferre_archive_metadata.json"),):
    if os.path.exists(candidate):
        try:
            with open(candidate, "r") as f:
                ferre_mappings = json.load(f)
            print(f"Loaded metadata mapping from {candidate}")
            break
        except Exception as e:
            print(f"Failed to load {candidate}: {e}")
            ferre_mappings = {}

def generate_query_embedding(query):
    """
    Generate an embedding vector for a single query string.

    Args:
        query (str): Input text query.

    Returns:
        List[float]:
            Embedding vector of shape (EMBEDDING_DIMENSION,).
    """

    kwargs = {
        "output_dimensionality": EMBEDDING_DIMENSION
    }
    response = llm_client.models.embed_content(
        model=EMBEDDING_MODEL,
        contents=query,
        config=types.EmbedContentConfig(**kwargs)
    )
    return response.embeddings[0].values


def generate_text_embeddings(chunks, dimensionality: int = 256, batch_size=250, max_retries=5, retry_delay=5):
    """
    Generate embeddings for a list of text chunks.

    Args:
        chunks (List[str]): Input text strings.
        dimensionality (int): Size of each embedding vector.
        batch_size (int): Max texts per API call.
        max_retries (int): Max retry attempts on API failure.
        retry_delay (int): Initial retry delay (seconds).

    Returns:
        List[List[float]]: 
            One embedding per input chunk.
            Shape: (len(chunks), dimensionality)
    """

    # Max batch size is 250 for Vertex AI
    all_embeddings = []

    for i in range(0, len(chunks), batch_size):
        batch = chunks[i:i+batch_size]

        # Retry logic with exponential backoff        pip list | grep langchain
        retry_count = 0
        while retry_count <= max_retries:
            try:
                response = llm_client.models.embed_content(
                    model=EMBEDDING_MODEL,
                    contents=batch,
                    config=types.EmbedContentConfig(
                        output_dimensionality=dimensionality),
                )
                all_embeddings.extend(
                    [embedding.values for embedding in response.embeddings])
                break

            except errors.APIError as e:
                retry_count += 1
                if retry_count > max_retries:
                    print(
                        f"Failed to generate embeddings after {max_retries} attempts. Last error: {str(e)}")
                    raise

                # Calculate delay with exponential backoff
                wait_time = retry_delay * (2 ** (retry_count - 1))
                print(
                    f"API error (code: {e.code}): {e.message}. Retrying in {wait_time} seconds (attempt {retry_count}/{max_retries})...")
                time.sleep(wait_time)

    return all_embeddings


def load_text_embeddings(df, collection, batch_size=500):
    """
    Load chunk embeddings, text, and metadata from a DataFrame
    into a vector database collection in batches.

    Args:
        df (pd.DataFrame):
            Must contain:
                - 'chunk' (str): text content
                - 'embedding' (List[float]): embedding vectors
                - 'doc' or 'book' (str): source identifier for metadata
        collection:
            Target vector database collection (must support .add()).
        batch_size (int): Number of items to insert per batch.

    Behavior:
        - Generates unique IDs using a hashed document/book prefix.
        - Builds per-chunk metadata (merging ferre_mappings if available).
        - Inserts ids, documents, embeddings, and metadata into the collection.
    """

    # Generate ids
    df["id"] = df.index.astype(str)

    # Determine key column: prefer 'doc' (PDF-derived), else 'book'
    key_col = "doc" if "doc" in df.columns else "book" if "book" in df.columns else None
    if key_col is None:
        raise ValueError("Dataframe must contain either 'doc' or 'book' column for metadata mapping")

    # Create hashed prefix from doc/book name
    hashed_keys = df[key_col].astype(str).apply(lambda x: hashlib.sha256(x.encode()).hexdigest()[:16])
    df["id"] = hashed_keys + "-" + df["id"]

    # Process data in batches
    total_inserted = 0
    for i in range(0, df.shape[0], batch_size):
        # Create a copy of the batch and reset the index
        batch = df.iloc[i:i+batch_size].copy().reset_index(drop=True)

        ids = batch["id"].tolist()
        documents = batch["chunk"].tolist()
        embeddings = batch["embedding"].tolist()

        # Build per-item metadata using ferre_mappings if available
        metadatas = []
        for key in batch[key_col].tolist():
            item_meta = {key_col: key}
            mapping_key = key
            if mapping_key in ferre_mappings:
                try:
                    # Merge mapping fields into item_meta
                    item_meta.update(ferre_mappings[mapping_key])
                except Exception:
                    pass
            metadatas.append(item_meta)

        collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas,
            embeddings=embeddings
        )
        total_inserted += len(batch)
        print(f"Inserted {total_inserted} items...")

    print(
        f"Finished inserting {total_inserted} items into collection '{collection.name}'")

# helper function for metadata filtering
def parse_filters(filter_args):
    """
    Parse repeatable CLI args like:
      --filter type=lesson --filter doc="Notes_White shirt"
    into a dict for Chroma 'where='.
    """
    if not filter_args:
        return None
    where = {}
    for s in filter_args:
        if "=" not in s:
            raise ValueError(f"Invalid --filter '{s}'. Use key=value.")
        k, v = s.split("=", 1)
        k = k.strip()
        v = v.strip().strip('"').strip("'")
        # cast ints when possible
        if v.isdigit():
            v = int(v)
        where[k] = v
    return where

# helper function for metadata filtering
# TODO: Move retrieve_chunks to agent_tools (or retrieval.py) once agent_tools is activated
def retrieve_chunks(collection, query_embedding, top_k=10, filters=None, contains=None):
    """
    Single source of truth for retrieval.
    Used by query(), chat(), and later agent tools.
    """
    kwargs = {
        "query_embeddings": [query_embedding],
        "n_results": top_k,
    }
    if filters:
        kwargs["where"] = filters
    if contains:
        kwargs["where_document"] = {"$contains": contains}
    return collection.query(**kwargs)


def chunk(method="recursive-split", source="pdf"):
    print("chunk()")

    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    if source == "pdf":
        pdf_dir = os.path.join(INPUT_FOLDER, "ferre-notes-lessons")
        pdf_files = glob.glob(os.path.join(pdf_dir, "*.pdf"))
        print("Number of PDFs to process:", len(pdf_files))

        for pdf_file in pdf_files:
            print("Processing PDF:", pdf_file)
            filename = os.path.basename(pdf_file)
            doc_name = os.path.splitext(filename)[0]

            try:
                doc = fitz.open(pdf_file)
            except Exception as e:
                print(f"Failed to open {pdf_file}: {e}")
                continue

            # Extract full text (or consider first N pages for metadata)
            input_text = "\n".join([p.get_text() for p in doc])

            text_chunks = None
            if method == "char-split":
                chunk_size = 350
                chunk_overlap = 20
                text_splitter = CharacterTextSplitter(
                    chunk_size=chunk_size, chunk_overlap=chunk_overlap, separator='', strip_whitespace=False)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "recursive-split":
                chunk_size = 350
                text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "semantic-split":
                text_splitter = SemanticChunker(embedding_function=generate_text_embeddings)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]

            if text_chunks is not None:
                data_df = pd.DataFrame(text_chunks, columns=["chunk"])
                data_df["chunk_index"] = range(len(data_df))  # add chunk_index for chunk-level filtering
                data_df["doc"] = doc_name
                print("Shape:", data_df.shape)
                print(data_df.head())
                jsonl_filename = os.path.join(OUTPUT_FOLDER, f"chunks-{method}-{doc_name}.jsonl")
                with open(jsonl_filename, "w") as json_file:
                    json_file.write(data_df.to_json(orient='records', lines=True))
    else:
        # Fallback to original text-based chunking
        text_files = glob.glob(os.path.join(INPUT_FOLDER, "books", "*.txt"))
        print("Number of text files to process:", len(text_files))
        for text_file in text_files:
            print("Processing file:", text_file)
            filename = os.path.basename(text_file)
            book_name = filename.split(".")[0]
            with open(text_file) as f:
                input_text = f.read()

            text_chunks = None
            if method == "char-split":
                chunk_size = 350
                chunk_overlap = 20
                text_splitter = CharacterTextSplitter(
                    chunk_size=chunk_size, chunk_overlap=chunk_overlap, separator='', strip_whitespace=False)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "recursive-split":
                chunk_size = 350
                text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "semantic-split":
                text_splitter = SemanticChunker(embedding_function=generate_text_embeddings)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]

            if text_chunks is not None:
                data_df = pd.DataFrame(text_chunks, columns=["chunk"])
                data_df["chunk_index"] = range(len(data_df))  # add chunk_index for chunk-level filtering
                data_df["book"] = book_name
                print("Shape:", data_df.shape)
                print(data_df.head())
                jsonl_filename = os.path.join(OUTPUT_FOLDER, f"chunks-{method}-{book_name}.jsonl")
                with open(jsonl_filename, "w") as json_file:
                    json_file.write(data_df.to_json(orient='records', lines=True))


def embed(method="recursive-split"):
    print("embed()")

    # Get the list of chunk files
    jsonl_files = glob.glob(os.path.join(
        OUTPUT_FOLDER, f"chunks-{method}-*.jsonl"))
    print("Number of files to process:", len(jsonl_files))

    # Process
    for jsonl_file in jsonl_files:
        print("Processing file:", jsonl_file)

        data_df = pd.read_json(jsonl_file, lines=True)
        print("Shape:", data_df.shape)
        print(data_df.head())

        chunks = data_df["chunk"].values
        chunks = chunks.tolist()
        if method == "semantic-split":
            embeddings = generate_text_embeddings(
                chunks, EMBEDDING_DIMENSION, batch_size=15)
        else:
            embeddings = generate_text_embeddings(
                chunks, EMBEDDING_DIMENSION, batch_size=100)
        data_df["embedding"] = embeddings

        time.sleep(5)

        # Save
        print("Shape:", data_df.shape)
        print(data_df.head())

        jsonl_filename = jsonl_file.replace("chunks-", "embeddings-")
        with open(jsonl_filename, "w") as json_file:
            json_file.write(data_df.to_json(orient='records', lines=True))


def load(method="recursive-split"):
    print("load()")

    # Clear Cache
    chromadb.api.client.SharedSystemClient.clear_system_cache()

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)

    # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
    collection_name = f"{method}-collection"
    print("Creating collection:", collection_name)

    try:
        # Clear out any existing items in the collection
        client.delete_collection(name=collection_name)
        print(f"Deleted existing collection '{collection_name}'")
    except Exception:
        print(f"Collection '{collection_name}' did not exist. Creating new.")

    collection = client.create_collection(
        name=collection_name, metadata={"hnsw:space": "cosine"})
    print(f"Created new empty collection '{collection_name}'")
    print("Collection:", collection)

    # Get the list of embedding files
    jsonl_files = glob.glob(os.path.join(
        OUTPUT_FOLDER, f"embeddings-{method}-*.jsonl"))
    print("Number of files to process:", len(jsonl_files))

    # Process
    for jsonl_file in jsonl_files:
        print("Processing file:", jsonl_file)

        data_df = pd.read_json(jsonl_file, lines=True)
        print("Shape:", data_df.shape)
        print(data_df.head())

        # Load data
        load_text_embeddings(data_df, collection)


def query(method="recursive-split", q=None, top_k=10, filters=None, contains=None):  # update query() to accept args + filters
    """
    Perform a similarity search on a Chroma collection using
    an embedded query, optionally applying metadata and lexical filters.

    Args:
        method (str): Collection prefix (used to construct collection name).

    Behavior:
        - Connects to ChromaDB.
        - Generates an embedding for a predefined query string.
        - Retrieves top-k similar chunks using:
            • Vector similarity
            • Optional metadata filter (where=...)
            • Optional lexical filter (where_document=...)
        - Prints retrieved results.
    """
    print("load()")

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)

    # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
    collection_name = f"{method}-collection"

    query = q or "What does Ferré say about creativity?"
    query_embedding = generate_query_embedding(query)
    print("Embedding values:", query_embedding)

    # Get the collection
    collection = client.get_collection(name=collection_name)
    

    results = retrieve_chunks(
        collection=collection,
        query_embedding=query_embedding,
        top_k=top_k,
        filters=filters,
        contains=contains,
    )

    # # 1: Query based on embedding value
    # results = collection.query(
    # 	query_embeddings=[query_embedding],
    # 	n_results=10
    # )
    # print("Query:", query)
    # print("\n\nResults:", results)

    # # 2: Query based on embedding value + metadata filter
    # results = collection.query(
    # 	query_embeddings=[query_embedding],
    # 	n_results=10,
    # 	where={"book":"The Complete Book of Cheese"}
    # )
    # print("Query:", query)
    # print("\n\nResults:", results)

    # # 3: Query based on embedding value + lexical search filter
    # search_string = "Italian"
    # results = collection.query(
    # 	query_embeddings=[query_embedding],
    # 	n_results=10,
    # 	where_document={"$contains": search_string}
    # )
    # print("Query:", query)
    # print("\n\nResults:", results)

    # 4: Query based on embedding value + lexical search filter
    # search_string = "Italian"
    # results = collection.query(
    #     query_embeddings=[query_embedding],
    #     n_results=10,
    #     where={"book": "The Complete Book of Cheese"},
    #     where_document={"$contains": search_string}
    # )
    print("Query:", query)
    print("Filters:", filters)
    print("\n\nResults:", results)


def chat(method="recursive-split", q=None, top_k=10, filters=None, contains=None):   # update chat() to accept args + filters
    """
    Run a simple RAG pipeline: retrieve relevant chunks and
    generate an LLM response using retrieved context.

    Args:
        method (str): Collection prefix (used to construct collection name).

    Behavior:
        - Connects to ChromaDB.
        - Embeds the user query.
        - Retrieves top-k similar documents from the collection.
        - Constructs a prompt combining the query and retrieved text.
        - Sends prompt to a generative LLM.
        - Prints the model's response.
    """
    print("chat()")

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)
    # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
    collection_name = f"{method}-collection"

    query = q or "Summarize Ferré's ideas in the archive."
    query_embedding = generate_query_embedding(query)
    print("Query:", query)
    print("Embedding values:", query_embedding)
    # Get the collection
    collection = client.get_collection(name=collection_name)
    

    results = retrieve_chunks(
        collection=collection,
        query_embedding=query_embedding,
        top_k=top_k,
        filters=filters,
        contains=contains,
    )
    # Query based on embedding value
    # results = collection.query(
    #     query_embeddings=[query_embedding],
    #     n_results=10
    # )
    print("\n\nResults:", results)

    print(len(results["documents"][0]))
    
    
    # update input prompt
    docs = results.get("documents", [[]])[0]
    if not docs:
        print("No documents retrieved.")
        return

    joined_docs = "\n\n".join(docs)

    INPUT_PROMPT = f"""
    {query}

    Context (retrieved chunks):
    {joined_docs}
    """
    
    # INPUT_PROMPT = f"""
	# {query}
	# {"\n".join(results["documents"][0])}
	# """

    print("INPUT_PROMPT: ", INPUT_PROMPT)
    response = llm_client.models.generate_content(
        model=GENERATIVE_MODEL,
        contents=INPUT_PROMPT,
        config=types.GenerateContentConfig(system_instruction=SYSTEM_INSTRUCTION),
    )
    generated_text = response.text

    print("LLM Response:", generated_text)


def get(method="recursive-split"):
    print("get()")

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)
    # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
    collection_name = f"{method}-collection"

    # Get the collection
    collection = client.get_collection(name=collection_name)

    # Get documents with filters
    results = collection.get(
        where={"book": "The Complete Book of Cheese"},
        limit=10
    )
    print("\n\nResults:", results)

def agent(method="recursive-split", q=None, top_k=10):
    """
    Agentic RAG pipeline: the LLM decides which retrieval tool(s) to call
    (and with what filters) based on the user query, then generates a final
    response from the retrieved chunks.

    Tools available to the LLM (defined in agent_tools.py):
      - search_archive:      general semantic search across all documents
      - search_by_type:      semantic search filtered by document type (lesson/note/archive)
      - search_by_document:  semantic search within a specific named document
    """
    print("agent()")

    # Connect to chroma DB
    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)
    collection_name = f"{method}-collection"
    collection = client.get_collection(name=collection_name)

    query = q or "What does Ferré say about creativity?"

    user_prompt_content = Content(
        role="user",
        parts=[Part(text=query)],
    )

    # Step 1: LLM chooses which tool(s) to call (mode="any" forces a tool call)
    print("User query:", query)
    response = llm_client.models.generate_content(
        model=GENERATIVE_MODEL,
        contents=user_prompt_content,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            temperature=0,
            tools=[agent_tools.ferre_expert_tool],
            tool_config=types.ToolConfig(
                function_calling_config=types.FunctionCallingConfig(mode="any")
            ),
        ),
    )
    print("LLM tool selection response:", response)

    # Step 2: Execute the selected tool(s) and retrieve chunks
    function_calls = [
        part.function_call
        for part in response.candidates[0].content.parts
        if part.function_call
    ]
    print("Function calls:", function_calls)

    function_responses = agent_tools.execute_function_calls(
        function_calls, collection, embed_func=generate_query_embedding, top_k=top_k
    )

    if not function_responses:
        print("No function responses returned — cannot generate answer.")
        return

    # Step 3: Feed retrieved chunks back to LLM for final answer
    final_response = llm_client.models.generate_content(
        model=GENERATIVE_MODEL,
        contents=[
            user_prompt_content,
            response.candidates[0].content,      # LLM's tool-call turn
            Content(parts=function_responses),   # tool results
        ],
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            tools=[agent_tools.ferre_expert_tool],
        ),
    )
    print("LLM Response:", final_response.text)


# Reference: original cheese-book agent (kept for reference)
# def agent(method="recursive-split"):
#     print("agent()")

#     # Connect to chroma DB
#     client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT)
#     # Get a collection object from an existing collection, by name. If it doesn't exist, create it.
#     collection_name = f"{method}-collection"
#     # Get the collection
#     collection = client.get_collection(name=collection_name)

#     # User prompt
#     user_prompt_content = Content(
#         role="user",
#         parts=[
#             Part(text="Describe where cheese making is important in Pavlos's book?"),
#         ],
#     )

#     # Step 1: Prompt LLM to find the tool(s) to execute to find the relevant chunks in vector db
#     print("user_prompt_content: ", user_prompt_content)
#     response = llm_client.models.generate_content(
#         model=GENERATIVE_MODEL,
#         contents=user_prompt_content,
#         config=types.GenerateContentConfig(
#             temperature=0,
#             tools=[agent_tools.cheese_expert_tool],
#             tool_config=types.ToolConfig(
#                 function_calling_config=types.FunctionCallingConfig(
#                     mode="any"
#                 )
#             )
#         )
#     )
#     print("LLM Response:", response)

#     # Step 2: Execute the function and send chunks back to LLM to answer get the final response
#     function_calls = [part.function_call for part in response.candidates[0].content.parts if part.function_call]
#     print("Function calls:", function_calls)
#     function_responses = agent_tools.execute_function_calls(
#         function_calls, collection, embed_func=generate_query_embedding)
#     if len(function_responses) == 0:
#         print("Function calls did not result in any responses...")
#     else:
#         # Call LLM with retrieved responses
#         response = llm_client.models.generate_content(
#             model=GENERATIVE_MODEL,
#             contents=[
#                 user_prompt_content,  # User prompt
#                 response.candidates[0].content,  # Function call response
#                 Content(
#                     parts=function_responses
#                 ),
#             ],
#             config=types.GenerateContentConfig(
#                 tools=[agent_tools.cheese_expert_tool]
#             )
#         )
#         print("LLM Response:", response)


def main(args=None):
    print("CLI Arguments:", args)

    if args.chunk:
        chunk(method=args.chunk_type)

    if args.embed:
        embed(method=args.chunk_type)

    if args.load:
        load(method=args.chunk_type)
    
    # wire the CLI flags
    filters = parse_filters(args.filter)
    if args.query:
        query(method=args.chunk_type, q=args.q, top_k=args.top_k, filters=filters, contains=args.contains)

    if args.chat:
        chat(method=args.chunk_type, q=args.q, top_k=args.top_k, filters=filters, contains=args.contains)
    # if args.query:
    #     query(method=args.chunk_type)

    # if args.chat:
    #     chat(method=args.chunk_type)

    if args.get:
        get(method=args.chunk_type)

    if args.agent:
        agent(method=args.chunk_type, q=args.q, top_k=args.top_k)


if __name__ == "__main__":
    # Generate the inputs arguments parser
    # if you type into the terminal '--help', it will provide the description
    parser = argparse.ArgumentParser(description="CLI")

    parser.add_argument(
        "--chunk",
        action="store_true",
        help="Chunk text",
    )
    parser.add_argument(
        "--embed",
        action="store_true",
        help="Generate embeddings",
    )
    parser.add_argument(
        "--load",
        action="store_true",
        help="Load embeddings to vector db",
    )
    parser.add_argument(
        "--query",
        action="store_true",
        help="Query vector db",
    )
    parser.add_argument(
        "--chat",
        action="store_true",
        help="Chat with LLM",
    )
    parser.add_argument(
        "--get",
        action="store_true",
        help="Get documents from vector db",
    )
    parser.add_argument(
        "--agent",
        action="store_true",
        help="Chat with LLM Agent",
    )
    parser.add_argument("--chunk_type", default="recursive-split",
                        help="char-split | recursive-split | semantic-split")
    
    # add new argparse options for metadata filtering
    parser.add_argument("--q", type=str, default=None, 
                        help="Query string")

    parser.add_argument("--top_k", type=int, default=10, 
                        help="Top K retrieval")

    parser.add_argument("--filter", action="append", default=[], 
                        help="Metadata filter key=value (repeatable)")

    parser.add_argument("--contains", type=str, default=None, 
                        help="Lexical contains filter on chunk text")

    args = parser.parse_args()

    main(args)
