import os
import argparse
import re
import glob
import json
import time
import hashlib
import unicodedata
import chromadb
import fitz  # PyMuPDF for PDF text extraction
import tiktoken
import pandas as pd
from pathlib import Path

from google import genai
from google.genai import types
from google.genai import errors
from vertexai.vision_models import Image, MultiModalEmbeddingModel

# Langchain
from langchain_text_splitters import CharacterTextSplitter, RecursiveCharacterTextSplitter
from semantic_splitter import SemanticChunker

# Token-based chunking: use cl100k_base (GPT-4 tokenizer) as a good approximation
# for text-embedding-004 (Google SentencePiece). Chunking defaults are expressed in tokens.
_tokenizer = tiktoken.get_encoding("cl100k_base")
CHUNK_SIZE_TOKENS = 350       # target: 300-400 tokens per chunk for Ferré archive texts
CHUNK_OVERLAP_TOKENS = 50     # ~14% overlap to preserve context across boundaries

def _token_len(text: str) -> int:
    return len(_tokenizer.encode(text))

# Setup
GCP_PROJECT = os.environ["GCP_PROJECT"]
GCP_LOCATION = "us-central1"
EMBEDDING_MODEL = "text-embedding-004"
EMBEDDING_DIMENSION = 256
GENERATIVE_MODEL = "gemini-2.0-flash-001"
INPUT_FOLDER = "input-datasets"
OUTPUT_FOLDER = "outputs"
CHROMADB_HOST = os.environ["CHROMADB_HOST"]
CHROMADB_PORT = int(os.environ.get("CHROMADB_PORT", "8000"))
CHROMADB_SSL = os.environ.get("CHROMADB_SSL", "false").lower() == "true"

llm_client = genai.Client(vertexai=True, project=GCP_PROJECT, location=GCP_LOCATION)

# System instruction for the CLI chat() command
SYSTEM_INSTRUCTION = """
You are an AI assistant specialized in Gianfranco Ferré and fashion archive research. Your responses are based solely on the information provided in the text chunks given to you. Do not use any external knowledge or make assumptions beyond what is explicitly stated in these chunks.

When answering a query:
1. Carefully read all the text chunks provided.
2. Identify the most relevant information from these chunks to address the user's question.
3. Formulate your response using only the information found in the given chunks.
4. If the provided chunks do not contain sufficient information to answer the query, state that you don't have enough information to provide a complete answer.
5. Always maintain a professional and knowledgeable tone, befitting a Ferré archive expert.
6. If there are contradictions in the provided chunks, mention this in your response and explain the different viewpoints presented.

Remember:
- You are an expert in Ferré and fashion, but your knowledge is limited to the information in the provided chunks.
- Do not invent information or draw from knowledge outside of the given text chunks.
- If asked about topics unrelated to Ferré or fashion, politely redirect the conversation back to archive-related subjects.
- Be concise in your responses while ensuring you cover all relevant information from the chunks.

Your goal is to provide accurate, helpful information about Ferré and fashion based solely on the content of the text chunks you receive with each query.
"""

# Load Ferre mappings if available (generated by temp_llm_metadata.py or manually)
ferre_mappings = {}
for candidate in ("ferre_mappings.json", "ferre_mappings_llm.json",
                  os.path.join("metadata", "ferre_archive_metadata.json")):
    if os.path.exists(candidate):
        try:
            with open(candidate, "r") as f:
                raw = json.load(f)
            # Normalize keys: strip .pdf suffix so they match the 'doc' field in ChromaDB
            ferre_mappings = {k.removesuffix(".pdf"): v for k, v in raw.items()}
            print(f"Loaded metadata mapping from {candidate}")
            break
        except Exception as e:
            print(f"Failed to load {candidate}: {e}")
            ferre_mappings = {}

def generate_query_embedding(query):
    """Generate an embedding vector for a single query string."""
    kwargs = {
        "output_dimensionality": EMBEDDING_DIMENSION
    }
    response = llm_client.models.embed_content(
        model=EMBEDDING_MODEL,
        contents=query,
        config=types.EmbedContentConfig(**kwargs)
    )
    return response.embeddings[0].values


def generate_text_embeddings(chunks, dimensionality: int = 256, batch_size=250, max_retries=5, retry_delay=5):
    """Generate embeddings for a list of text chunks. Max batch size 250 (Vertex AI limit)."""
    all_embeddings = []

    for i in range(0, len(chunks), batch_size):
        batch = chunks[i:i+batch_size]

        # Retry logic with exponential backoff
        retry_count = 0
        while retry_count <= max_retries:
            try:
                response = llm_client.models.embed_content(
                    model=EMBEDDING_MODEL,
                    contents=batch,
                    config=types.EmbedContentConfig(
                        output_dimensionality=dimensionality),
                )
                all_embeddings.extend(
                    [embedding.values for embedding in response.embeddings])
                break

            except errors.APIError as e:
                retry_count += 1
                if retry_count > max_retries:
                    print(
                        f"Failed to generate embeddings after {max_retries} attempts. Last error: {str(e)}")
                    raise

                # Calculate delay with exponential backoff
                wait_time = retry_delay * (2 ** (retry_count - 1))
                print(
                    f"API error (code: {e.code}): {e.message}. Retrying in {wait_time} seconds (attempt {retry_count}/{max_retries})...")
                time.sleep(wait_time)

    return all_embeddings


def load_text_embeddings(df, collection, batch_size=500):
    """Load chunk embeddings and metadata into a ChromaDB collection.

    df must have 'chunk', 'embedding', and 'doc'/'book' columns.
    IDs are sha256-hashed from the source name. Metadata is enriched from ferre_mappings if loaded.
    """
    # Generate ids
    df["id"] = df.index.astype(str)

    # Determine key column: prefer 'doc' (PDF-derived), else 'book'
    key_col = "doc" if "doc" in df.columns else "book" if "book" in df.columns else None
    if key_col is None:
        raise ValueError("Dataframe must contain either 'doc' or 'book' column for metadata mapping")

    hashed_keys = df[key_col].astype(str).apply(lambda x: hashlib.sha256(x.encode()).hexdigest()[:16])
    df["id"] = hashed_keys + "-" + df["id"]

    total_inserted = 0
    for i in range(0, df.shape[0], batch_size):
        batch = df.iloc[i:i+batch_size].copy().reset_index(drop=True)

        ids = batch["id"].tolist()
        documents = batch["chunk"].tolist()
        embeddings = batch["embedding"].tolist()

        # Build per-item metadata using ferre_mappings if available
        metadatas = []
        for key in batch[key_col].tolist():
            item_meta = {key_col: key}
            mapping_key = key
            if mapping_key in ferre_mappings:
                try:
                    for k, v in ferre_mappings[mapping_key].items():
                        if v is None:
                            continue  # ChromaDB does not accept None
                        if isinstance(v, list):
                            v = ", ".join(str(i) for i in v)  # e.g. main_topics list
                        item_meta[k] = v
                except Exception:
                    pass
            metadatas.append(item_meta)

        collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas,
            embeddings=embeddings
        )
        total_inserted += len(batch)
        print(f"Inserted {total_inserted} items...")

    print(
        f"Finished inserting {total_inserted} items into collection '{collection.name}'")
    
def parse_filters(filter_args):
    """Parse --filter key=value args into a ChromaDB where dict."""
    if not filter_args:
        return None
    where = {}
    for s in filter_args:
        if "=" not in s:
            raise ValueError(f"Invalid --filter '{s}'. Use key=value.")
        k, v = s.split("=", 1)
        k = k.strip()
        v = v.strip().strip('"').strip("'")
        # cast ints when possible
        if v.isdigit():
            v = int(v)
        where[k] = v
    return where

def retrieve_chunks(collection, query_embedding, top_k=10, filters=None, contains=None):
    """Run a vector similarity query against a ChromaDB collection."""
    kwargs = {
        "query_embeddings": [query_embedding],
        "n_results": top_k,
    }
    if filters:
        kwargs["where"] = filters
    if contains:
        kwargs["where_document"] = {"$contains": contains}
    return collection.query(**kwargs)




def chunk(method="recursive-split", source="pdf", skip_existing=False):
    print("chunk()")

    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    if source == "pdf":
        pdf_dirs = [
            os.path.join(INPUT_FOLDER, "ferre-notes-lessons"),
            os.path.join(INPUT_FOLDER, "ferre-press-releases"),
        ]
        pdf_files = []
        for pdf_dir in pdf_dirs:
            if os.path.isdir(pdf_dir):
                pdf_files.extend(glob.glob(os.path.join(pdf_dir, "*.pdf")))
        print("Number of PDFs to process:", len(pdf_files))

        for pdf_file in pdf_files:
            filename = os.path.basename(pdf_file)
            doc_name = os.path.splitext(filename)[0]
            jsonl_filename = os.path.join(OUTPUT_FOLDER, f"chunks-{method}-{doc_name}.jsonl")

            if skip_existing and os.path.exists(jsonl_filename):
                print(f"Skipping (already chunked): {filename}")
                continue

            print("Processing PDF:", pdf_file)

            try:
                doc = fitz.open(pdf_file)
            except Exception as e:
                print(f"Failed to open {pdf_file}: {e}")
                continue

            input_text = "\n".join([p.get_text() for p in doc])

            text_chunks = None
            if method == "char-split":
                text_splitter = CharacterTextSplitter(
                    chunk_size=CHUNK_SIZE_TOKENS,
                    chunk_overlap=CHUNK_OVERLAP_TOKENS,
                    separator='',
                    strip_whitespace=False,
                    length_function=_token_len,
                )
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "recursive-split":
                text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
                    encoding_name="cl100k_base",
                    chunk_size=CHUNK_SIZE_TOKENS,
                    chunk_overlap=CHUNK_OVERLAP_TOKENS,
                )
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "semantic-split":
                text_splitter = SemanticChunker(embedding_function=generate_text_embeddings)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]

            if text_chunks is not None:
                data_df = pd.DataFrame(text_chunks, columns=["chunk"])
                data_df["doc"] = doc_name
                print("Shape:", data_df.shape)
                print(data_df.head())
                jsonl_filename = os.path.join(OUTPUT_FOLDER, f"chunks-{method}-{doc_name}.jsonl")
                with open(jsonl_filename, "w") as json_file:
                    json_file.write(data_df.to_json(orient='records', lines=True))
    else:
        # Fallback to original text-based chunking
        text_files = glob.glob(os.path.join(INPUT_FOLDER, "books", "*.txt"))
        print("Number of text files to process:", len(text_files))
        for text_file in text_files:
            print("Processing file:", text_file)
            filename = os.path.basename(text_file)
            book_name = filename.split(".")[0]
            with open(text_file) as f:
                input_text = f.read()

            text_chunks = None
            if method == "char-split":
                text_splitter = CharacterTextSplitter(
                    chunk_size=CHUNK_SIZE_TOKENS,
                    chunk_overlap=CHUNK_OVERLAP_TOKENS,
                    separator='',
                    strip_whitespace=False,
                    length_function=_token_len,
                )
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "recursive-split":
                text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
                    encoding_name="cl100k_base",
                    chunk_size=CHUNK_SIZE_TOKENS,
                    chunk_overlap=CHUNK_OVERLAP_TOKENS,
                )
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]
            elif method == "semantic-split":
                text_splitter = SemanticChunker(embedding_function=generate_text_embeddings)
                text_chunks = text_splitter.create_documents([input_text])
                text_chunks = [d.page_content for d in text_chunks]

            if text_chunks is not None:
                data_df = pd.DataFrame(text_chunks, columns=["chunk"])
                data_df["book"] = book_name
                print("Shape:", data_df.shape)
                print(data_df.head())
                jsonl_filename = os.path.join(OUTPUT_FOLDER, f"chunks-{method}-{book_name}.jsonl")
                with open(jsonl_filename, "w") as json_file:
                    json_file.write(data_df.to_json(orient='records', lines=True))


def embed(method="recursive-split", skip_existing=False):
    print("embed()")

    jsonl_files = glob.glob(os.path.join(
        OUTPUT_FOLDER, f"chunks-{method}-*.jsonl"))
    print("Number of files to process:", len(jsonl_files))

    for jsonl_file in jsonl_files:
        embeddings_filename = jsonl_file.replace("chunks-", "embeddings-")
        if skip_existing and os.path.exists(embeddings_filename):
            print(f"Skipping (already embedded): {os.path.basename(jsonl_file)}")
            continue

        print("Processing file:", jsonl_file)

        data_df = pd.read_json(jsonl_file, lines=True)
        print("Shape:", data_df.shape)
        print(data_df.head())

        chunks = data_df["chunk"].values
        chunks = chunks.tolist()
        if method == "semantic-split":
            embeddings = generate_text_embeddings(
                chunks, EMBEDDING_DIMENSION, batch_size=15)
        else:
            embeddings = generate_text_embeddings(
                chunks, EMBEDDING_DIMENSION, batch_size=100)
        data_df["embedding"] = embeddings

        time.sleep(5)

        # Save
        print("Shape:", data_df.shape)
        print(data_df.head())

        jsonl_filename = jsonl_file.replace("chunks-", "embeddings-")
        with open(jsonl_filename, "w") as json_file:
            json_file.write(data_df.to_json(orient='records', lines=True))


def generate_image_embeddings(image_paths, batch_size=1, max_retries=1, retry_delay=5):
    """Generate 1408-dim multimodal embeddings for images using Vertex AI."""
    import vertexai

    # Initialize Vertex AI
    vertexai.init(project=GCP_PROJECT, location=GCP_LOCATION)
    model = MultiModalEmbeddingModel.from_pretrained("multimodalembedding@001")

    all_embeddings = []
    failed_count = 0

    for idx, img_path in enumerate(image_paths, 1):
        try:
            filename = Path(img_path).name

            # Retry logic with exponential backoff
            retry_count = 0
            success = False
            while retry_count <= max_retries:
                try:
                    # Load image using Vertex AI Image class
                    image = Image.load_from_file(img_path)

                    # Use the multimodal embedding model to get embeddings
                    response = model.get_embeddings(
                        image=image,
                        dimension=1408
                    )

                    if response and response.image_embedding:
                        all_embeddings.append(response.image_embedding)
                        print(f"  [{idx}/{len(image_paths)}] ✓ {filename}")
                        success = True
                        break
                    else:
                        raise ValueError(f"No embeddings returned for {filename}")

                except Exception as e:
                    retry_count += 1
                    if retry_count > max_retries:
                        print(f"  [{idx}/{len(image_paths)}] ✗ {filename} - Failed after {max_retries} retries: {str(e)}")
                        failed_count += 1
                        break

                    # Calculate delay with exponential backoff
                    wait_time = retry_delay * (2 ** (retry_count - 1))
                    print(f"  [{idx}/{len(image_paths)}] Retrying {filename} in {wait_time}s... (attempt {retry_count}/{max_retries})")
                    time.sleep(wait_time)

        except Exception as e:
            print(f"  [{idx}/{len(image_paths)}] ✗ Error processing {Path(img_path).name}: {e}")
            failed_count += 1

    print(f"\n✓ Generated {len(all_embeddings)} embeddings ({failed_count} failed)")
    return all_embeddings

def embed_fashion_show_photos(images_folder="Dataset DataShack 2026"):
    """Generate embeddings for fashion show photos organized by season folders."""
    print(f"embed_fashion_show_photos() - Processing images from {images_folder}")
    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    # Find all image files and group by season folder
    image_extensions = ('*.jpg', '*.jpeg', '*.png', '*.gif', '*.webp')
    seasons_data = {}  # {season_key: [image_paths]}

    for root, dirs, files in os.walk(images_folder):
        # Only process images inside a "Fashion show photos" subfolder (case-insensitive)
        path_parts = os.path.relpath(root, images_folder).split(os.sep)
        if not any(part.lower() == "fashion show photos" for part in path_parts):
            continue

        for file in files:
            if any(file.lower().endswith(ext.replace('*', '')) for ext in image_extensions):
                img_path = os.path.join(root, file)

                # Extract season from parent folder name like "ALTA MODA 1986-87 FW"
                # Look for the season folder (e.g., "ALTA MODA 1986-87 FW" or "ALTA MODA 1989 SS")
                season_folder = "unknown"
                for i, p in enumerate(path_parts):
                    # Match pattern like "ALTA MODA <year> <season>" or "ALTA MODA <years> <season>"
                    if re.match(r'^ALTA MODA.*(\d{4}(?:-\d{2})?)\s+(FW|SS)', p, re.IGNORECASE):
                        season_folder = p
                        break

                if season_folder not in seasons_data:
                    seasons_data[season_folder] = []
                seasons_data[season_folder].append(img_path)

    if not seasons_data:
        print(f"⚠ No image files found in {images_folder}")
        return

    print(f"Found {sum(len(v) for v in seasons_data.values())} image files across {len(seasons_data)} seasons")
    print(f"Seasons: {', '.join(sorted(seasons_data.keys()))}")

    # Process each season
    for season_folder, image_files in sorted(seasons_data.items()):
        print(f"\n→ Processing season: {season_folder} ({len(image_files)} images)")

        image_files = sorted(image_files)

        # Generate embeddings for this season
        embeddings = generate_image_embeddings(image_files)

        # Create dataframe with image metadata
        data = []
        for img_path, embedding in zip(image_files, embeddings):
            filename = os.path.basename(img_path)
            rel_path = os.path.relpath(img_path, images_folder)

            data.append({
                "id": hashlib.md5(rel_path.encode()).hexdigest(),
                "filename": filename,
                "path": img_path,
                "season": season_folder,
                "embedding": embedding,
                "text": f"{season_folder} - {filename}"  # For text-based querying
            })

        # Save embeddings for this season
        output_file = os.path.join(OUTPUT_FOLDER, f"embeddings-images-{season_folder}-fashion-show-photos.jsonl")
        df = pd.DataFrame(data)

        with open(output_file, "w") as f:
            f.write(df.to_json(orient='records', lines=True))

        print(f"  ✓ Saved {len(df)} embeddings to {output_file}")

    print(f"\n✓ Image embeddings complete for all {len(seasons_data)} seasons")


def load(method="recursive-split"):
    print("load()")

    # Clear Cache
    chromadb.api.client.SharedSystemClient.clear_system_cache()

    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT, ssl=CHROMADB_SSL)
    collection_name = f"{method}-collection"
    print("Creating collection:", collection_name)

    try:
        client.delete_collection(name=collection_name)
        print(f"Deleted existing collection '{collection_name}'")
    except Exception:
        print(f"Collection '{collection_name}' did not exist. Creating new.")

    collection = client.create_collection(
        name=collection_name, metadata={"hnsw:space": "cosine"})
    print(f"Created new empty collection '{collection_name}'")

    jsonl_files = glob.glob(os.path.join(
        OUTPUT_FOLDER, f"embeddings-{method}-*.jsonl"))
    print("Number of files to process:", len(jsonl_files))

    for jsonl_file in jsonl_files:
        print("Processing file:", jsonl_file)

        data_df = pd.read_json(jsonl_file, lines=True)
        print("Shape:", data_df.shape)
        print(data_df.head())

        # Load data
        load_text_embeddings(data_df, collection)


def load_fashion_show_photos():
    """Load fashion show photo embeddings into ChromaDB as a single collection.

    Each record is enriched with metadata from generated_image_metadata_final.jsonl,
    joined on embedding['path'] == metadata['source_path'].
    """
    print("load_fashion_show_photos()")

    COLLECTION_NAME = "images-fashion-show-photos"
    METADATA_FILE = os.path.join(
        "metadata", "images_metadata", "final_metadata_generation",
        "generated_image_metadata_final.jsonl"
    )

    # Load rich metadata keyed by NFC-normalized source_path for O(1) lookup.
    # Normalization avoids mismatches when the same character (e.g. é) is encoded
    # as a single codepoint (NFC) in one file and as base+combining accent (NFD) in another.
    metadata_by_path = {}
    if os.path.exists(METADATA_FILE):
        with open(METADATA_FILE, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    record = json.loads(line)
                    key = unicodedata.normalize("NFC", record["source_path"])
                    metadata_by_path[key] = record
        print(f"✓ Loaded {len(metadata_by_path)} metadata records from {METADATA_FILE}")
    else:
        print(f"⚠ Metadata file not found: {METADATA_FILE}. Loading with basic metadata only.")

    # Tag fields stored as comma-separated strings (ChromaDB does not support lists)
    TAG_FIELDS = [
        "garments_tags", "colors_tags", "material_tags", "patterns_tags",
        "silhouette_tags", "length_tags", "neckline_tags", "sleeve_tags",
        "closure_tags", "embellishment_tags", "style_tags",
    ]
    SCALAR_FIELDS = [
        "season_path", "year_path", "collection_line", "asset_type", "cluster_id", "outfit_id",
        "llm_description", "pdf_available", "season", "label", "acquisition",
        "look", "file", "inventory", "object", "source", "description",
        "exhibitions", "size", "materials", "present_location", "remark",
        "bibliography", "designer", "working_process", "condition", "collection", "year",
    ]

    def build_metadata(row, path: str) -> dict:
        """Build metadata from the rich metadata record, keyed by source_path."""
        meta = {"source_path": path}
        rich = metadata_by_path.get(path)
        if rich:
            for field in SCALAR_FIELDS:
                meta[field] = str(rich.get(field) or "")
            for field in TAG_FIELDS:
                tags = rich.get(field) or []
                meta[field] = ", ".join(tags) if isinstance(tags, list) else str(tags)
        return meta

    # Clear Cache
    chromadb.api.client.SharedSystemClient.clear_system_cache()

    # Connect to ChromaDB with retry logic
    max_retries = 10
    retry_delay = 1
    client = None
    for attempt in range(max_retries):
        try:
            client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT, ssl=CHROMADB_SSL)
            print(f"✓ Connected to ChromaDB on attempt {attempt + 1}")
            break
        except (ValueError, ConnectionError) as e:
            if attempt < max_retries - 1:
                print(f"⚠ ChromaDB not ready (attempt {attempt + 1}/{max_retries}), retrying in {retry_delay}s...")
                time.sleep(retry_delay)
                retry_delay = min(retry_delay * 1.5, 5)
            else:
                print(f"✗ Failed to connect to ChromaDB after {max_retries} attempts")
                raise

    if client is None:
        raise RuntimeError("Failed to connect to ChromaDB")

    embedding_files = glob.glob(os.path.join(OUTPUT_FOLDER, "embeddings-images-*-fashion-show-photos.jsonl"))
    if not embedding_files:
        print(f"⚠ No fashion show photo embeddings found in {OUTPUT_FOLDER}. Run --embed-fashion-show-photos first.")
        return

    print(f"Found {len(embedding_files)} season file(s) to load into '{COLLECTION_NAME}'")

    try:
        client.delete_collection(name=COLLECTION_NAME)
        print(f"Deleted existing collection '{COLLECTION_NAME}'")
    except Exception:
        pass

    collection = client.create_collection(name=COLLECTION_NAME, metadata={"hnsw:space": "cosine"})
    print(f"Created collection '{COLLECTION_NAME}'")

    total_loaded = 0
    unmatched = 0
    for jsonl_file in sorted(embedding_files):
        season = (
            os.path.basename(jsonl_file)
            .replace("embeddings-images-", "")
            .replace("-fashion-show-photos.jsonl", "")
        )
        print(f"\n→ Loading season: {season} from {jsonl_file}")
        data_df = pd.read_json(jsonl_file, lines=True)

        if "id" not in data_df.columns:
            data_df["id"] = data_df["filename"].astype(str)

        batch_size = 500
        for i in range(0, data_df.shape[0], batch_size):
            batch = data_df.iloc[i:i+batch_size].copy().reset_index(drop=True)
            ids = batch["id"].tolist()
            embeddings = batch["embedding"].tolist()
            metadatas = []
            documents = []
            for _, row in batch.iterrows():
                path = unicodedata.normalize("NFC", str(row.get("path", "")))
                if path and path not in metadata_by_path:
                    unmatched += 1
                metadatas.append(build_metadata(row, path))
                # Build a tag document string for $contains filtering via where_document.
                # All tag values are joined into a single searchable text field.
                rich = metadata_by_path.get(path)
                if rich:
                    all_tags = []
                    for field in TAG_FIELDS:
                        tags = rich.get(field) or []
                        if isinstance(tags, list):
                            all_tags.extend(tags)
                    documents.append(" ".join(all_tags) if all_tags else str(row.get("filename", "")))
                else:
                    documents.append(str(row.get("filename", "")))
            collection.add(ids=ids, documents=documents, metadatas=metadatas, embeddings=embeddings)

        total_loaded += len(data_df)
        print(f"  ✓ Loaded {len(data_df)} images")

    print(f"\n✓ Total loaded: {total_loaded} images")
    if unmatched:
        print(f"⚠ {unmatched} embeddings had no matching metadata record (stored with basic metadata only)")

    print(f"\n✓ Fashion show photos loading complete. Total: {total_loaded} images across {len(embedding_files)} seasons into '{COLLECTION_NAME}'")


def query(method="recursive-split", q=None, top_k=10, filters=None, contains=None):
    """Print top-k similar chunks from ChromaDB for a query string."""
    print("query()")

    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT, ssl=CHROMADB_SSL)
    collection_name = f"{method}-collection"

    query = q or "What does Ferré say about creativity?"
    query_embedding = generate_query_embedding(query)
    print("Embedding values:", query_embedding)

    # Get the collection
    collection = client.get_collection(name=collection_name)

    results = retrieve_chunks(
        collection=collection,
        query_embedding=query_embedding,
        top_k=top_k,
        filters=filters,
        contains=contains,
    )

    print("Query:", query)
    print("Filters:", filters)
    print("\n\nResults:", results)


def chat(method="recursive-split", q=None, top_k=10, filters=None, contains=None):
    """Retrieve top-k chunks and generate an LLM response (RAG)."""
    print("chat()")

    client = chromadb.HttpClient(host=CHROMADB_HOST, port=CHROMADB_PORT, ssl=CHROMADB_SSL)
    collection_name = f"{method}-collection"

    query = q or "Summarize Ferré's ideas in the archive."
    query_embedding = generate_query_embedding(query)
    print("Query:", query)
    print("Embedding values:", query_embedding)
    # Get the collection
    collection = client.get_collection(name=collection_name)

    results = retrieve_chunks(
        collection=collection,
        query_embedding=query_embedding,
        top_k=top_k,
        filters=filters,
        contains=contains,
    )
    print("\n\nResults:", results)

    docs = results.get("documents", [[]])[0]
    if not docs:
        print("No documents retrieved.")
        return

    joined_docs = "\n\n".join(docs)

    INPUT_PROMPT = f"""
    {query}

    Context (retrieved chunks):
    {joined_docs}
    """

    print("INPUT_PROMPT: ", INPUT_PROMPT)
    response = llm_client.models.generate_content(
        model=GENERATIVE_MODEL,
        contents=INPUT_PROMPT,
        config=types.GenerateContentConfig(system_instruction=SYSTEM_INSTRUCTION),
    )
    generated_text = response.text

    print("LLM Response:", generated_text)

def main(args=None):
    print("CLI Arguments:", args)

    if args.chunk:
        chunk(method=args.chunk_type, skip_existing=args.skip_existing)

    if args.embed:
        embed(method=args.chunk_type, skip_existing=args.skip_existing)

    if args.embed_fashion_show_photos:
        embed_fashion_show_photos()

    if args.load:
        load(method=args.chunk_type)

    if args.load_fashion_show_photos:
        load_fashion_show_photos()

     # wire the CLI flags
    filters = parse_filters(args.filter)
    if args.query:
        query(method=args.chunk_type, q=args.q, top_k=args.top_k, filters=filters, contains=args.contains)

    if args.chat:
        chat(method=args.chunk_type, q=args.q, top_k=args.top_k, filters=filters, contains=args.contains)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CLI")

    parser.add_argument(
        "--chunk",
        action="store_true",
        help="Chunk text",
    )
    parser.add_argument(
        "--embed",
        action="store_true",
        help="Generate embeddings",
    )
    parser.add_argument(
        "--load",
        action="store_true",
        help="Load embeddings to vector db",
    )
    parser.add_argument(
        "--query",
        action="store_true",
        help="Query vector db",
    )
    parser.add_argument(
        "--chat",
        action="store_true",
        help="Chat with LLM",
    )
    parser.add_argument(
        "--embed-fashion-show-photos",
        action="store_true",
        help="Generate embeddings for fashion show photos (Alta Moda seasons)",
    )
    parser.add_argument(
        "--load-fashion-show-photos",
        action="store_true",
        help="Load fashion show photo embeddings into ChromaDB (single collection: images-fashion-show-photos)",
    )
    parser.add_argument("--chunk_type", default="semantic-split",
                        help="char-split | recursive-split | semantic-split")

    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="Skip PDFs/chunks whose output file already exists (incremental processing)",
    )
    parser.add_argument("--q", type=str, default=None, 
                        help="Query string")

    parser.add_argument("--top_k", type=int, default=10, 
                        help="Top K retrieval")

    parser.add_argument("--filter", action="append", default=[], 
                        help="Metadata filter key=value (repeatable)")

    parser.add_argument("--contains", type=str, default=None, 
                        help="Lexical contains filter on chunk text")

    args = parser.parse_args()

    main(args)
