networks:
    default:
        name: llm-rag-network
        external: true
services:
    llm-rag-cli:
        build: .
        image: llm-rag-cli
        container_name: llm-rag-cli
        volumes:
            - .:/app
            - ../../../secrets:/secrets
            - ./input-datasets:/app/input-datasets
            - ./outputs:/app/outputs
            - ./metadata:/app/metadata
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
            CHROMADB_HOST: llm-rag-chromadb
            CHROMADB_PORT: 8000
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: llm-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
